### ISSUE TITLE
macOS Sierra: CloudinaryImageType.js:19 generateFilename: () => undefined,

### ISSUE THREAD

**Issue by mstranieri** [JedWatson/sydjs-site#106]
Hello,
I have been downloaded Sydjs from Git pull and there is a trouble when I try to run "node keystone":

/Users/mstranieri/Documents/sites/raven/node_modules/keystone/fields/types/cloudinaryimage/CloudinaryImageType.js:19
	generateFilename: () => undefined,
	                   ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mstranieri/Documents/sites/raven/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.CloudinaryImage (/Users/mstranieri/Documents/sites/raven/node_modules/keystone/lib/fieldTypes.js:4:34)
    at Object.<anonymous> (/Users/mstranieri/Documents/sites/raven/models/Organisation.js:16:21)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mstranieri/Documents/sites/raven/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
 

Anyone can help me?

MacBook-Air-di-Marco-Stranieri:raven mstranieri$ npm -v
3.10.3
MacBook-Air-di-Marco-Stranieri:raven mstranieri$ node -v
v0.12.0

**Comment by Guziq** [comment]
@mstranieri KeystoneJS 4 is not compatible with **0.12.x** and lower versions of node
