### ISSUE TITLE
passport.initialize() middleware not in use

### ISSUE THREAD

**Issue by martonic** [JedWatson/sydjs-site#29]
I cloned the site to bitnami mean stack 64-bit on EC2.
- mongoDB 2.6.0
- RockMongo 1.1.5
- Apache 2.4.9
- PHP 5.4.26
- Node.js 0.10.26

The clone works, but I can't join with Facebook (this is not a problem on the official site, it is only a problem on the cloned site).

I put valid Cloudinary and Facebook credentials in the .env file.

Here are the diagnostics.

Error: passport.initialize() middleware not in use
  at IncomingMessage.req.login.req.logIn (/home/bitnami/sydjs/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport/lib/passport/http/request.js:30:30)
  at Strategy.strategy.success (/home/bitnami/sydjs/node_modules/passport/lib/middleware/authenticate.js:228:13)
  at verified (/home/bitnami/sydjs/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:179:18)
  at Strategy._verify (/home/bitnami/sydjs/lib/auth/facebook.js:27:3)
  at /home/bitnami/sydjs/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:195:22
  at /home/bitnami/sydjs/node_modules/passport-facebook/lib/strategy.js:183:5
  at passBackControl (/home/bitnami/sydjs/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:126:9)
  at IncomingMessage.<anonymous> (/home/bitnami/sydjs/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
  at IncomingMessage.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:920:16
  at process._tickCallback (node.js:415:13)

Any will be tremendously appreciated!

**Comment by TechRapport** [comment]
Nice.  This helped me a lot.  Thank you.
