### ISSUE TITLE
OAuth2Strategy requires a clientID option while Social Sign-In

### ISSUE THREAD

**Issue by SanthoshVijayabaskar** [JedWatson/sydjs-site#30]
Hi,

I tried setup the code and when i try to login/sign-up using social links, I get the OAuth2Strategy error. Can I get help on how to configure Client ID and how to resolve this issue.

Thanks in advance.

Issue Log

TypeError: OAuth2Strategy requires a clientID option
  at Strategy.OAuth2Strategy (/opt/run/snapshot/package/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:83:34)
  at new Strategy (/opt/run/snapshot/package/node_modules/passport-facebook/lib/strategy.js:55:18)
  at Object.exports.authenticateUser (/opt/run/snapshot/package/lib/auth/facebook.js:26:25)
  at module.exports (/opt/run/snapshot/package/routes/auth/service.js:23:31)
  at callbacks (/opt/run/snapshot/package/node_modules/keystone/node_modules/express/lib/router/index.js:164:37)
  at param (/opt/run/snapshot/package/node_modules/keystone/node_modules/express/lib/router/index.js:138:11)
  at param (/opt/run/snapshot/package/node_modules/keystone/node_modules/express/lib/router/index.js:135:11)
  at pass (/opt/run/snapshot/package/node_modules/keystone/node_modules/express/lib/router/index.js:145:5)
  at Router._dispatch (/opt/run/snapshot/package/node_modules/keystone/node_modules/express/lib/router/index.js:173:5)
  at Object.router (/opt/run/snapshot/package/node_modules/keystone/node_modules/express/lib/router/index.js:33:10)
  at next (/opt/run/snapshot/package/node_modules/keystone/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Promise.<anonymous> (/opt/run/snapshot/package/routes/middleware.js:50:3)
  at Promise.<anonymous> (/opt/run/snapshot/package/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
  at Promise.emit (events.js:95:17)
  at Promise.emit (/opt/run/snapshot/package/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
  at Promise.fulfill (/opt/run/snapshot/package/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
  at Promise.resolve (/opt/run/snapshot/package/node_modules/keystone/node_modules/mongoose/lib/promise.js:108:15)
  at Promise.<anonymous> (/opt/run/snapshot/package/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
  at Promise.emit (events.js:95:17)
  at Promise.emit (/opt/run/snapshot/package/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
  at Promise.fulfill (/opt/run/snapshot/package/node_modules/keystone/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
  at Object.cb (/opt/run/snapshot/package/node_modules/keystone/node_modules/mongoose/lib/query.js:1010:22)
  at Object._onImmediate (/opt/run/snapshot/package/node_modules/keystone/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
  at processImmediate [as _immediateCallback](timers.js:336:15)

**Comment by hungcaoduy** [comment]
I got the same error message, but simply I used the wrong key (some kind of typo: Id instead of ID)
