### ISSUE TITLE
Trouble integrating Twitter & Facebook

### ISSUE THREAD

**Issue by andybridges** [JedWatson/sydjs-site#59]
Hi, 

I'm having a bit of trouble trying to integrate facebook and twitter, I've been using the SydJS repository as a guide but I feel like I must have missed a step somewhere, here is the current error message I am getting when I attempt to login with Twitter...

TypeError: OAuthStrategy requires a consumerKey option at Strategy.OAuthStrategy (/node/convo/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:83:37) at new Strategy (/node/convo/node_modules/passport-twitter/lib/strategy.js:53:17) at Object.exports.authenticateUser (/node/convo/lib/auth/twitter.js:29:24) at module.exports (/node/convo/routes/auth/service.js:21:31) at Layer.handle [as handle_request] (/node/convo/node_modules/keystone/node_modules/express/lib/router/layer.js:82:5) at next (/node/convo/node_modules/keystone/node_modules/express/lib/router/route.js:110:13) at Route.dispatch (/node/convo/node_modules/keystone/node_modules/express/lib/router/route.js:91:3) at Layer.handle [as handle_request] (/node/convo/node_modules/keystone/node_modules/express/lib/router/layer.js:82:5) at /node/convo/node_modules/keystone/node_modules/express/lib/router/index.js:267:22 at param (/node/convo/node_modules/keystone/node_modules/express/lib/router/index.js:340:14) at param (/node/convo/node_modules/keystone/node_modules/express/lib/router/index.js:356:14) at Function.proto.process_params (/node/convo/node_modules/keystone/node_modules/express/lib/router/index.js:400:3) at next (/node/convo/node_modules/keystone/node_modules/express/lib/router/index.js:261:10) at next (/node/convo/node_modules/keystone/node_modules/express/lib/router/route.js:100:14) at next (/node/convo/node_modules/keystone/node_modules/express/lib/router/route.js:104:14) at next (/node/convo/node_modules/keystone/node_modules/express/lib/router/route.js:104:14)

Any help would be greatly appreciated. 

Thanks

**Comment by andybridges** [comment]
I'm thinking this may have something to do with my local env?

**Comment by inagaraj** [comment]
@andybridges how to set variables in .env file..
