### ISSUE TITLE
Error: 500:: GET /js/home.js - syntax issue in client/scripts/home.js

### ISSUE THREAD

**Issue by wjh000123** [JedWatson/sydjs-site#76]
Dear,
I've searched the solution for the issue but still got nothing, so I come here to disturb you. I followed the steps and got the site up, everything is OK except for the 500 error for the home.js. After my research, it's syntax issue that browserify cannot recognize jsx, but the view engine is Jade, seems that the transform option in browserify-middleware doesn't work. Is there any solution for this?
I'm using node@v4.1.1, npm@3.5.1.

```
SyntaxError: D:/dy/sydjs/client/components/HeroApp.js: Unexpected token (40:10)
  38 |  renderWelcome: function() {
  39 |          if (this.state.rsvp.attending) {
> 40 |                  return <h4 className="hero-button-title"><span className = "welcome-message">See you there!</span></h4>
     |           ^
  41 |          } else {
  42 |                  return <h4 className="hero-button-title">Are you coming? <br /> <span className="spots-left">{this.state.meetup.remainingRSVPs}<span className="text-thin"> spots left</span></span><br /></h4>
  43 |          }
    at Parser.pp.raise (D:\dy\sydjs\node_modules\babylon\lib\parser\location.js:22:13)
    at Parser.pp.unexpected (D:\dy\sydjs\node_modules\babylon\lib\parser\util.js:91:8)
    at Parser.pp.parseExprAtom (D:\dy\sydjs\node_modules\babylon\lib\parser\expression.js:510:12)
    at Parser.pp.parseExprSubscripts (D:\dy\sydjs\node_modules\babylon\lib\parser\expression.js:265:19)
    at Parser.pp.parseMaybeUnary (D:\dy\sydjs\node_modules\babylon\lib\parser\expression.js:245:19)
    at Parser.pp.parseExprOps (D:\dy\sydjs\node_modules\babylon\lib\parser\expression.js:176:19)
    at Parser.pp.parseMaybeConditional (D:\dy\sydjs\node_modules\babylon\lib\parser\expression.js:158:19)
    at Parser.pp.parseMaybeAssign (D:\dy\sydjs\node_modules\babylon\lib\parser\expression.js:121:19)
    at Parser.pp.parseExpression (D:\dy\sydjs\node_modules\babylon\lib\parser\expression.js:85:19)
    at Parser.pp.parseReturnStatement (D:\dy\sydjs\node_modules\babylon\lib\parser\statement.js:313:26)
    at Parser.pp.parseStatement (D:\dy\sydjs\node_modules\babylon\lib\parser\statement.js:101:19)
    at Parser.pp.parseBlockBody (D:\dy\sydjs\node_modules\babylon\lib\parser\statement.js:527:25)
    at Parser.pp.parseBlock (D:\dy\sydjs\node_modules\babylon\lib\parser\statement.js:482:8)
    at Parser.pp.parseStatement (D:\dy\sydjs\node_modules\babylon\lib\parser\statement.js:121:19)
    at Parser.pp.parseIfStatement (D:\dy\sydjs\node_modules\babylon\lib\parser\statement.js:294:26)
    at Parser.pp.parseStatement (D:\dy\sydjs\node_modules\babylon\lib\parser\statement.js:99:19)
    at Parser.pp.parseBlockBody (D:\dy\sydjs\node_modules\babylon\lib\parser\statement.js:527:25)
    at Parser.pp.parseBlock (D:\dy\sydjs\node_modules\babylon\lib\parser\statement.js:482:8)
    at Parser.pp.parseFunctionBody (D:\dy\sydjs\node_modules\babylon\lib\parser\expression.js:886:22)
    at Parser.pp.parseFunction (D:\dy\sydjs\node_modules\babylon\lib\parser\statement.js:620:8)
    at Parser.pp.parseFunctionExpression (D:\dy\sydjs\node_modules\babylon\lib\parser\expression.js:520:17)
    at Parser.pp.parseExprAtom (D:\dy\sydjs\node_modules\babylon\lib\parser\expression.js:482:19)
```

**Comment by wjh000123** [comment]
OK, solved the problem by downgrade the babelify version to ^6.4.0, might be the compatibility issue. Issue closed.

**Comment by wjh000123** [comment]
And here's another solution for people who intend to use the latest version of babelify (it's preferred):
1). after `npm install`, also `npm install --save-dev babel-preset-react`
2). then update line#49 of /routes/index.js to:
`transform: [['babelify', {presets: ["react"]}]],`
