### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by ceddyb** [JedWatson/sydjs-site#79]
Hi Jed,
 Been searching for this on the internet, i followed all your steps 
when i run $ node keystone 
i get this   

Thanks 
  
     /home/ceddy/node js/sydjs-site/node_modules/keystone/admin/server/middleware/logError.js:7
		var msg = `[${endpoint}]`;
		          ^
    SyntaxError: Unexpected token ILLEGAL
        at exports.runInThisContext (vm.js:73:16)
       at Module._compile (module.js:443:25)
       at Module._extensions..js (module.js:478:10)
       at Object.require.extensions.(anonymous function) [as .js] (/home/ceddy/node js/sydjs-    site/node_modules/babel-register/lib/node.js:138:7)
       at Module.load (module.js:355:32)
       at Function.Module._load (module.js:310:12)
       at Module.require (module.js:365:17)
       at require (module.js:384:17)
       at Object.createDynamicRouter (/home/ceddy/node js/sydjs-    site/node_modules/keystone/admin/server/app/createDynamicRouter.js:65:21)
        at createApp (/home/ceddy/node js/sydjs-site/node_modules/keystone/server/createApp.js:63:72)
       at [object Object].initExpressApp (/home/ceddy/node js/sydjs-    site/node_modules/keystone/lib/core/initExpressApp.js:5:46)
        at [object Object].start (/home/ceddy/node js/sydjs-     site/node_modules/keystone/lib/core/start.js:47:7)
        at Object.<anonymous> (/home/ceddy/node js/sydjs-site/keystone.js:94:10)
        at Module._compile (module.js:460:26)
       at Object.Module._extensions..js (module.js:478:10)
       at Module.load (module.js:355:32)
       at Function.Module._load (module.js:310:12)
       at Function.Module.runMain (module.js:501:10)
       at startup (node.js:129:16)
       at node.js:814:3

**Comment by ceddyb** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart sydjs-site@3.0.0
6 info start sydjs-site@3.0.0
7 verbose unsafe-perm in lifecycle true
8 info sydjs-site@3.0.0 Failed to exec start script
9 verbose stack Error: sydjs-site@3.0.0 start: `node keystone.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid sydjs-site@3.0.0
11 verbose cwd /home/ceddy/syd/sydjs
12 error Linux 4.2.0-21-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error sydjs-site@3.0.0 start: `node keystone.js`
17 error Exit status 1
18 error Failed at the sydjs-site@3.0.0 start script 'node keystone.js'.
18 error This is most likely a problem with the sydjs-site package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node keystone.js
18 error You can get their info via:
18 error     npm owner ls sydjs-site
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ceddyb** [comment]
Hey i got it working, 

I was running it with $node v0.12.7 which seemed to not support template strings, so i had to run it with $nodejs v4.2.3 Everything works great now.
