### ISSUE TITLE
google + login issue

### ISSUE THREAD

**Issue by oliverwh** [JedWatson/sydjs-site#99]
This one stopped working. I assume due to some google updates.

**Comment by 13MaxG** [comment]
`TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/app/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/app/node_modules/passport-facebook/lib/strategy.js:54:18)
    at Object.exports.authenticateUser (/app/lib/auth/facebook.js:30:25)
    at module.exports (/app/routes/auth/service.js:23:31)
    at Layer.handle [as handle_request] (/app/node_modules/keystone/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/keystone/node_modules/express/lib/router/route.js:131:13)
    at next (/app/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
    at next (/app/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
    at next (/app/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
    at next (/app/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
    at Route.dispatch (/app/node_modules/keystone/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/keystone/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/keystone/node_modules/express/lib/router/index.js:277:22
    at param (/app/node_modules/keystone/node_modules/express/lib/router/index.js:349:14)
    at param (/app/node_modules/keystone/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/app/node_modules/keystone/node_modules/express/lib/router/index.js:410:3)
    at next (/app/node_modules/keystone/node_modules/express/lib/router/index.js:271:10)
    at safeDone (/app/node_modules/keystone/node_modules/grappling-hook/index.js:201:9)
    at /app/node_modules/keystone/node_modules/grappling-hook/index.js:256:4
    at /app/node_modules/keystone/node_modules/grappling-hook/node_modules/async/lib/async.js:154:25
    at /app/routes/middleware.js:61:3
    at Query.<anonymous> (/app/node_modules/keystone/node_modules/mongoose/lib/query.js:2181:28)`

Same error for Google+, Facebook and Twitter rejestraction.

**Comment by vadimk-design** [comment]
@13MaxG  what about variables in your .env file for this social providers? this error usually appear if it's not set or set uncorrecttly

**Comment by inagaraj** [comment]
@vkudyushev  @13MaxG  where i put social logins client ids and secret key.. please give some solutions..

**Comment by herbowicz** [comment]
> @vkudyushev @13MaxG where i put social logins client ids and secret key.. please give some solutions..

Hi @inagaraj, most likely you need to add to them to your .env file, but that part is missing in README

**Comment by herbowicz** [comment]
@inagaraj These constants are used in files located in `/lib/auth`.  For example in facebook.js:
```
var credentials = {
	clientID: process.env.FACEBOOK_CLIENT_ID,
	clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
	callbackURL: process.env.FACEBOOK_CALLBACK_URL
};
```
Define [them](https://gist.github.com/herbowicz/9cd2843a8fb240d59897e952e575268e) in `.env` file.
